# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

namePrefix: prod-

resources:
  - ../../bases/catalog-svc
  - namespace.yaml

patchesStrategicMerge:
  - replicas.yaml